name: Build and Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [created, edited, published]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Set Qt host
      id: qt_host
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          echo "host=windows" >> $GITHUB_OUTPUT
        elif [ "${{ runner.os }}" == "macOS" ]; then
          echo "host=mac" >> $GITHUB_OUTPUT
        else
          echo "host=linux" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: ${{ steps.qt_host.outputs.host }}
        target: 'desktop'

    - name: Build (Linux & macOS)
      if: runner.os != 'Windows'
      run: |
        qmake
        make

    - name: Build (Windows)
      if: runner.os == 'Windows'
      run: |
        qmake
        nmake

    - name: Deploy (Linux)
      if: runner.os == 'Linux'
      run: |
        mkdir -p appdir/usr/bin
        cp FloatingBall appdir/usr/bin/
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage
        ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/bin/FloatingBall -appimage

    - name: Deploy (macOS)
      if: runner.os == 'macOS'
      run: |
        macdeployqt FloatingBall.app -dmg

    - name: Deploy (Windows)
      if: runner.os == 'Windows'
      run: |
        windeployqt release/FloatingBall.exe
        7z a FloatingBall-windows.zip release/

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          FloatingBall*.AppImage
          FloatingBall.dmg
          FloatingBall-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
